<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <AssemblyName>BlackoutServer</AssemblyName>
    <RootNamespace>BlackoutServer</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Version>2.1.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="SPTarkov.DI">
      <HintPath>$(SPT_PATH)\SPT\SPTarkov.DI.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="SPTarkov.Server.Core">
      <HintPath>$(SPT_PATH)\SPT\SPTarkov.Server.Core.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="SPTarkov.Common">
      <HintPath>$(SPT_PATH)\SPT\SPTarkov.Common.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="SemanticVersioning">
      <HintPath>$(SPT_PATH)\SPT\SemanticVersioning.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="WTT-ServerCommonLib">
      <HintPath>$(SPT_PATH)\SPT\user\mods\WTT-ServerCommonLib\WTT-ServerCommonLib.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="MoreBotsServer">
      <HintPath>$(SPT_PATH)\SPT\user\mods\MoreBotsServer\MoreBotsServer.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

</Project>
